version: '3.8'

services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: wordpress-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password123}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
    networks:
      - wordpress-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
  # Redis para cache de alta performance
  redis:
    image: redis:7-alpine
    container_name: wordpress-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "/etc/redis/redis.conf", "--requirepass", "password123"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password123}
    volumes:
      - ./data/redis:/data
      - ./redis/conf:/etc/redis:ro
    networks:
      - wordpress-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
  # WordPress com LiteSpeed
  wordpress:
    build: .
    container_name: wordpress-litespeed
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "7080:7080"
    environment:
      # MySQL Configuration
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password123}
      
      # WordPress Configuration
      WP_TABLE_PREFIX: ${WP_TABLE_PREFIX:-wpx_}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-false}
      
      # Redis Configuration  
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password123}
      REDIS_DB: ${REDIS_DB:-0}
      
      # LiteSpeed Configuration
      LSWS_ADMIN_PASS: ${LSWS_ADMIN_PASS:-password123}
      
      # Performance Settings
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-512M}
      PHP_UPLOAD_MAX_SIZE: ${PHP_UPLOAD_MAX_SIZE:-128M}
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:-600}
      
      # SSL/Domain
      DOMAIN: ${DOMAIN:-localhost}
      
    volumes:
      - ./data/wordpress:/var/www/html
      - ./wordpress/uploads.ini:/etc/php/8.2/fpm/conf.d/uploads.ini:ro
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - wordpress-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # phpMyAdmin para gerenciar banco
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wordpress-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER:-wordpress}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-password123}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password123}
      UPLOAD_LIMIT: 128M
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 600
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wordpress-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

# Volumes nomeados para persistência
volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local
  redis_data:
    driver: local

# Rede customizada com configurações de segurança
networks:
  wordpress-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1 